#!/bin/bash

set -u

INTERFACE="eth0"
PORT="8080"

function fetchEnvironmentParams()
{
    if [ "" != "${HTTPSHARE_DEFAULT_PORT-""}" ]; then PORT="${HTTPSHARE_DEFAULT_PORT}"; fi
    if [ "" != "${HTTPSHARE_DEFAULT_INTERFACE-""}" ]; then INTERFACE="${HTTPSHARE_DEFAULT_INTERFACE}"; fi
}

function getParamFromFile()
{
    local CONFIGFILE="$1"
    local KEY="$2"
    local DEFAULTVALUE="$3"

    local KEYGREPSTRING="^[[:space:]]*${KEY}[[:space:]]*=[[:space:]]*"
    if grep "${KEYGREPSTRING}" "${CONFIGFILE}" > /dev/null ; then
        grep "${KEYGREPSTRING}" "${CONFIGFILE}" | sed "s/${KEYGREPSTRING}//"
        return 0
    fi
    echo "${DEFAULTVALUE}"
    return 1
}

function fetchConfigFileParams()
{
	local CONFIGFILE="$1"
	test -r "${CONFIGFILE}" || return 1
    PORT="$(getParamFromFile "${CONFIGFILE}" "PORT" "${PORT}")"
    INTERFACE="$(getParamFromFile "${CONFIGFILE}" "INTERFACE" "${INTERFACE}")"
}

function fetchCmdlineParams()
{
	#while getopts ":i:p:" --long "interface:,port:" opt; do
	while getopts ":i:p:" opt; do
	    case ${opt} in
	        i|interface)
	            INTERFACE="${OPTARG}"
	            ;;
	        p)
	            PORT="${OPTARG}"
	            ;;
	        \?)
	            echo "Invalid option: -$OPTARG" >&2
	            exit 1
	            ;;
	        :)
	            echo "Option -$OPTARG requires an argument." >&2
	            exit 1
	            ;;
	    esac
	done
}

function doShare()
{
	local URL=$(ifconfig | grep "${INTERFACE}" -A 1 | grep "inet addr" | sed 's/^[[:space:]]*//g' | awk '-F[ :]' '{print $3}' | sed 's,\(.*\),http://\1:'"${PORT},")
	echo "$URL"
	echo -n "$URL" | qr

	python -m SimpleHTTPServer "${PORT}"
}

fetchConfigFileParams "/etc/httpShare/config"
fetchConfigFileParams "${HOME}/.config/httpShare/config"
fetchEnvironmentParams
fetchCmdlineParams "$@"

echo Sharing on port ${PORT} getting IP address from ${INTERFACE}

